### ISSUE TITLE
ERROR! couldn't resolve module/action 'amazon.aws.ec2_vpc_net'

### ISSUE THREAD

**Issue by mikecebul** [hauben/ansible-play-strapi#1]
Excuse my lack my ignorance at GitHub norms, I'm kind of a noob. 

I've been looking for this process to work and be automated so I was ecstatic to come across your repository in a forum today. I tried the Strapi docs to deploy on AWS and couldn't get it to run. So I'm trying this. I followed the instructions to a T (I on;y left out the recommended key encryption with vault) and even started with a brand new Ubuntu droplet to run everything to eliminate variables. 

When I run 
ansible-playbook ./site.yml
I get a permission error

So I run it with 
sudo ansible-playbook ./site.yml
and I get this in my logs...

-------------------------------------------
2021-08-01 05:32:07,452 p=15625 u=root n=ansible | [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

2021-08-01 05:32:07,664 p=15625 u=root n=ansible | ERROR! couldn't resolve module/action 'amazon.aws.ec2_vpc_net'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/mike/ansible-strapi-aws/roles/vpc/tasks/create_vpc.yml': line 2, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

# Create the VPC
- name: Create a VPC
  ^ here
---------------------------------------------

-- I double checked and I left out VPC full access to my AWS user, but I get the same error after adding the permission.

Any help would be greatly appreciated.

**Comment by hauben** [comment]
Hi!

Sorry for my late reply. I was on vacation.

Please check in /inventories/development/group_vars/all/credentials.yml that there you have setup the aws_access_key and aws_secret_key which you have created before on your AWS account. It seems that the problem is that you cannot connect to AWS at all. The VPC is the first part which gets generated so its "normal" that this step fails first.

Please let me know if you have any problems ....

Cheers
Frank
